import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

type AlertLevel = "WATCH_LONG" | "WATCH_SHORT" | "READY_LONG" | "READY_SHORT" | "DATA_WARNING" | "NO_ALERT";

type AnalysisResponse = {
  ok?: boolean;
  error?: string;
  snapshot_id?: string;
  symbol?: string;
  timeframe?: string;
  current?: { ts?: string; close?: number; regime?: string };
  probabilities?: {
    bull?: number;
    bear?: number;
    sideways?: number;
    directional_edge?: number;
    persistence?: number;
  };
  decision?: {
    action?: string;
    title?: string;
    detail?: string;
    bias?: string;
    reasons?: string[];
  };
  data_quality?: { score?: number; issues?: string[] };
};

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
};

const DEFAULT_WATCHLIST = ["XAUUSD", "BTC-USD", "SPY", "QQQ", "AAPL", "NVDA", "MSFT", "TSLA"];
const DEFAULT_TIMEFRAMES = ["1D", "4H", "1H"];

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data, null, 2), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function pct(value: number | undefined) {
  return `${Math.round((Number(value) || 0) * 100)}%`;
}

function money(value: number | undefined) {
  const n = Number(value);
  if (!Number.isFinite(n)) return "n/a";
  return n.toLocaleString(undefined, { maximumFractionDigits: n > 1000 ? 0 : 2 });
}

function getAlertLevel(analysis: AnalysisResponse): AlertLevel {
  const q = Number(analysis.data_quality?.score ?? 0);
  const current = analysis.current?.regime || "Sideways";
  const action = analysis.decision?.action || "WAIT";
  const bull = Number(analysis.probabilities?.bull || 0);
  const bear = Number(analysis.probabilities?.bear || 0);
  const edge = Number(analysis.probabilities?.directional_edge || 0);

  if (q < 80 || action === "IGNORE") return "DATA_WARNING";
  if (action === "READY_LONG") return "READY_LONG";
  if (action === "READY_SHORT") return "READY_SHORT";
  if (current === "Bull" && bull >= 0.7 && edge >= 0.3) return "WATCH_LONG";
  if (current === "Bear" && bear >= 0.7 && edge <= -0.3) return "WATCH_SHORT";
  return "NO_ALERT";
}

function alertTitle(level: AlertLevel) {
  switch (level) {
    case "WATCH_LONG": return "🍌 WATCH LONG";
    case "WATCH_SHORT": return "🍌 WATCH SHORT";
    case "READY_LONG": return "🚀 READY LONG";
    case "READY_SHORT": return "🔻 READY SHORT";
    case "DATA_WARNING": return "⚠️ DATA WARNING";
    default: return "NO ALERT";
  }
}

function shouldSend(level: AlertLevel, includeDataWarnings: boolean) {
  if (level === "NO_ALERT") return false;
  if (level === "DATA_WARNING") return includeDataWarnings;
  return true;
}

function buildTelegramMessage(analysis: AnalysisResponse, level: AlertLevel) {
  const symbol = analysis.symbol || "UNKNOWN";
  const tf = analysis.timeframe || "?";
  const title = alertTitle(level);
  const regime = analysis.current?.regime || "n/a";
  const close = money(analysis.current?.close);
  const bull = pct(analysis.probabilities?.bull);
  const bear = pct(analysis.probabilities?.bear);
  const edge = pct(analysis.probabilities?.directional_edge);
  const quality = analysis.data_quality?.score ?? "n/a";
  const action = analysis.decision?.action || "WAIT";
  const detail = analysis.decision?.detail || "Context alert generated by Trade Banana.";

  return [
    `${title} — ${symbol} ${tf}`,
    "",
    `Regime: ${regime}`,
    `Last close: ${close}`,
    `Bull Next: ${bull}`,
    `Bear Next: ${bear}`,
    `Directional Edge: ${edge}`,
    `Data Quality: ${quality}%`,
    `Trade Permission: ${action}`,
    "",
    detail,
    "",
    "Peel back the charts. Find the good stuff.",
    "Decision support only — not financial advice."
  ].join("\n");
}

async function sendTelegram(text: string) {
  const token = Deno.env.get("TELEGRAM_BOT_TOKEN");
  const chatId = Deno.env.get("TELEGRAM_CHAT_ID");
  if (!token || !chatId) {
    return { sent: false, error: "Telegram secrets are missing" };
  }

  const response = await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ chat_id: chatId, text, disable_web_page_preview: true }),
  });

  const payload = await response.json().catch(() => ({}));
  if (!response.ok || payload.ok === false) {
    return { sent: false, error: payload.description || `Telegram HTTP ${response.status}` };
  }
  return { sent: true, error: null };
}

async function runAnalysis(symbol: string, timeframe: string, serviceRole: string, supabaseUrl: string) {
  const res = await fetch(`${supabaseUrl}/functions/v1/flowstate-analysis`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "apikey": serviceRole,
      "Authorization": `Bearer ${serviceRole}`,
    },
    body: JSON.stringify({ symbol, timeframe, execution_confirmed: false, outputsize: 5000 }),
  });

  const data = await res.json().catch(() => ({}));
  if (!res.ok || data.error) throw new Error(data.error || `flowstate-analysis failed: HTTP ${res.status}`);
  return data as AnalysisResponse;
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRole = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceRole, { auth: { persistSession: false } });

    let body: Record<string, unknown> = {};
    if (req.method === "POST") {
      try { body = await req.json(); } catch (_) { body = {}; }
    }

    if (body.test === true) {
      const telegram = await sendTelegram([
        "🍌 Trade Banana Telegram test",
        "",
        "Connection confirmed.",
        "Supabase Edge Function can reach Telegram.",
        "Decision support only — not financial advice."
      ].join("\n"));
      return json({ ok: telegram.sent, test: true, telegram });
    }

    const symbols = Array.isArray(body.symbols) && body.symbols.length ? body.symbols.map(String) : DEFAULT_WATCHLIST;
    const timeframes = Array.isArray(body.timeframes) && body.timeframes.length ? body.timeframes.map((x) => String(x).toUpperCase()) : DEFAULT_TIMEFRAMES;
    const includeDataWarnings = body.include_data_warnings === true;
    const results: unknown[] = [];

    for (const symbol of symbols) {
      for (const timeframe of timeframes) {
        try {
          const analysis = await runAnalysis(symbol, timeframe, serviceRole, supabaseUrl);
          const level = getAlertLevel(analysis);

          if (!shouldSend(level, includeDataWarnings)) {
            results.push({ symbol, timeframe, level, sent: false, skipped: true });
            continue;
          }

          const asOf = analysis.current?.ts || new Date().toISOString();
          const dedupeKey = `${symbol}:${timeframe}:${level}:${asOf}`;
          const message = buildTelegramMessage({ ...analysis, symbol, timeframe }, level);

          const { data: existing } = await supabase
            .from("trade_banana_alert_events")
            .select("id, telegram_sent")
            .eq("dedupe_key", dedupeKey)
            .maybeSingle();

          if (existing?.telegram_sent) {
            results.push({ symbol, timeframe, level, sent: false, skipped: "duplicate" });
            continue;
          }

          const telegram = await sendTelegram(message);
          const eventPayload = {
            symbol,
            timeframe,
            alert_level: level,
            current_regime: analysis.current?.regime ?? null,
            current_close: analysis.current?.close ?? null,
            bull_probability: analysis.probabilities?.bull ?? null,
            bear_probability: analysis.probabilities?.bear ?? null,
            directional_edge: analysis.probabilities?.directional_edge ?? null,
            data_quality_score: analysis.data_quality?.score ?? null,
            source_snapshot_id: analysis.snapshot_id ?? null,
            as_of: asOf,
            telegram_sent: telegram.sent,
            telegram_error: telegram.error,
            dedupe_key: dedupeKey,
            payload: { analysis, telegram_message: message },
          };

          const { error: upsertError } = await supabase
            .from("trade_banana_alert_events")
            .upsert(eventPayload, { onConflict: "dedupe_key" });
          if (upsertError) throw upsertError;

          results.push({ symbol, timeframe, level, sent: telegram.sent, error: telegram.error });
        } catch (error) {
          results.push({ symbol, timeframe, error: error instanceof Error ? error.message : String(error) });
        }
      }
    }

    return json({ ok: true, results });
  } catch (error) {
    console.error(error);
    return json({ ok: false, error: error instanceof Error ? error.message : String(error) }, 500);
  }
});
